import fs from 'node:fs'

const [inputPath, outputPath] = process.argv.slice(2)
if (!inputPath || !outputPath) {
  throw new Error('usage: node tools/token-gen/token-gen.mjs <constants.ts> <tokens.rs>')
}

const source = fs.readFileSync(inputPath, 'utf8')

const single = evalArray(extractArray('SINGLE_BYTE_TOKENS'))
const double = evalArray(extractArray('DOUBLE_BYTE_TOKENS'))

const rendered = [
  '// @generated by tools/token-gen. Do not edit by hand.',
  '',
  '#[derive(Clone, Copy, Debug, Eq, PartialEq)]',
  'pub struct Token {',
  '    pub dict: Option<u8>,',
  '    pub index: u8,',
  '}',
  '',
  'pub static SINGLE_BYTE_TOKENS: &[&str] = &[',
  ...single.map((token) => `    ${JSON.stringify(token)},`),
  '];',
  '',
  'pub static DOUBLE_BYTE_TOKENS: &[&[&str]] = &[',
  ...double.flatMap((dict) => [
    '    &[',
    ...dict.map((token) => `        ${JSON.stringify(token)},`),
    '    ],',
  ]),
  '];',
  '',
  'pub fn token_for(value: &str) -> Option<Token> {',
  '    for (index, token) in SINGLE_BYTE_TOKENS.iter().enumerate() {',
  '        if *token == value {',
  '            return Some(Token { dict: None, index: index as u8 });',
  '        }',
  '    }',
  '',
  '    for (dict, tokens) in DOUBLE_BYTE_TOKENS.iter().enumerate() {',
  '        for (index, token) in tokens.iter().enumerate() {',
  '            if *token == value {',
  '                return Some(Token { dict: Some(dict as u8), index: index as u8 });',
  '            }',
  '        }',
  '    }',
  '',
  '    None',
  '}',
  '',
  'pub fn single_token(index: u8) -> Option<&\'static str> {',
  '    SINGLE_BYTE_TOKENS.get(index as usize).copied()',
  '}',
  '',
  'pub fn double_token(dict: u8, index: u8) -> Option<&\'static str> {',
  '    DOUBLE_BYTE_TOKENS',
  '        .get(dict as usize)',
  '        .and_then(|tokens| tokens.get(index as usize))',
  '        .copied()',
  '}',
  '',
].join('\n')

fs.writeFileSync(outputPath, rendered)

function extractArray(name) {
  const marker = `export const ${name} = [`
  const start = source.indexOf(marker)
  if (start < 0) {
    throw new Error(`array not found: ${name}`)
  }

  let index = source.indexOf('[', start)
  let depth = 0
  let quote = null
  let escaped = false
  for (; index < source.length; index++) {
    const ch = source[index]
    if (quote) {
      if (escaped) {
        escaped = false
      } else if (ch === '\\') {
        escaped = true
      } else if (ch === quote) {
        quote = null
      }
      continue
    }

    if (ch === '"' || ch === "'") {
      quote = ch
      continue
    }

    if (ch === '[') {
      depth += 1
    } else if (ch === ']') {
      depth -= 1
      if (depth === 0) {
        return source.slice(source.indexOf('[', start), index + 1)
      }
    }
  }

  throw new Error(`unterminated array: ${name}`)
}

function evalArray(arrayText) {
  return Function(`"use strict"; return (${arrayText});`)()
}
