use std::env;
use std::fs;
use std::path::PathBuf;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut raw_args = env::args().skip(1).collect::<Vec<_>>();
    let check = matches!(raw_args.first().map(String::as_str), Some("--check"));
    if check {
        raw_args.remove(0);
    }
    let mut args = raw_args.into_iter();
    let proto = PathBuf::from(args.next().ok_or("missing proto path argument")?);
    let out = PathBuf::from(
        args.next()
            .ok_or("missing generated output path argument")?,
    );
    let temp = env::temp_dir().join("wa-proto-gen");

    if temp.exists() {
        fs::remove_dir_all(&temp)?;
    }
    fs::create_dir_all(&temp)?;

    let patched_proto = temp.join("WAProto.patched.proto");
    let source = fs::read_to_string(&proto)?;
    fs::write(&patched_proto, patch_proto3_enums(&source))?;

    let protoc = protoc_bin_vendored::protoc_bin_path()?;
    let mut config = prost_build::Config::new();
    config.out_dir(&temp);
    config.bytes(["."]);
    config.protoc_executable(protoc);
    config.compile_protos(&[patched_proto], std::slice::from_ref(&temp))?;

    let generated = temp.join("proto.rs");
    let mut content = fs::read_to_string(generated)?;
    content.insert_str(
        0,
        "// @generated by tools/proto-gen. Do not edit by hand.\n",
    );
    if check {
        let existing = fs::read_to_string(&out)?;
        if existing != content {
            return Err(format!("generated protobuf output is stale: {}", out.display()).into());
        }
    } else {
        fs::write(out, content)?;
    }
    Ok(())
}

fn patch_proto3_enums(source: &str) -> String {
    let mut out = Vec::new();
    let mut lines = source.lines().peekable();
    let mut zero_counter = 0usize;

    while let Some(line) = lines.next() {
        out.push(line.to_owned());
        let trimmed = line.trim_start();
        if !trimmed.starts_with("enum ") || !trimmed.ends_with('{') {
            continue;
        }

        let indent = line
            .chars()
            .take_while(|ch| ch.is_whitespace())
            .collect::<String>();
        let value_indent = format!("{indent}    ");
        let mut pending = Vec::new();
        let mut first_value: Option<i64> = None;

        while let Some(enum_line) = lines.peek().copied() {
            let enum_trimmed = enum_line.trim();
            if enum_trimmed.starts_with('}') {
                break;
            }

            if let Some(value) = parse_enum_value(enum_trimmed) {
                first_value = Some(value);
                break;
            }

            pending.push(lines.next().expect("peeked line must exist").to_owned());
        }

        if first_value.is_some_and(|value| value != 0) {
            out.push(format!("{value_indent}WA_PROTO_ZERO_{zero_counter} = 0;"));
            zero_counter += 1;
        }

        out.extend(pending);
    }

    let mut rendered = out.join("\n");
    rendered.push('\n');
    rendered
}

fn parse_enum_value(line: &str) -> Option<i64> {
    if line.is_empty()
        || line.starts_with("//")
        || line.starts_with("/*")
        || line.starts_with("option ")
        || line.starts_with("reserved ")
    {
        return None;
    }

    let (_, rhs) = line.split_once('=')?;
    let number = rhs
        .split(|ch: char| !(ch == '-' || ch.is_ascii_digit()))
        .find(|part| !part.is_empty())?;
    number.parse().ok()
}

#[cfg(test)]
mod tests {
    use super::patch_proto3_enums;

    #[test]
    fn inserts_zero_for_non_zero_first_enum_value() {
        let source = "syntax = \"proto3\";\nenum Test {\n  ONE = 1;\n}\n";
        let patched = patch_proto3_enums(source);
        assert!(patched.contains("WA_PROTO_ZERO_0 = 0;"));
    }

    #[test]
    fn keeps_zero_first_enum_unchanged() {
        let source = "syntax = \"proto3\";\nenum Test {\n  ZERO = 0;\n}\n";
        let patched = patch_proto3_enums(source);
        assert!(!patched.contains("WA_PROTO_ZERO_0 = 0;"));
    }
}
